### ISSUE TITLE
Is repo deprecated?

### ISSUE THREAD

**Issue by chilipepperhott** [Steppenwolfe65/NTRU-NET#2]
I am trying to find an NTRU implementation, but I want to make sure that this is still following the specification. Is it?

**Comment by Steppenwolfe65** [comment]
Sorry for the delay (I don't go online much anymore..).
All of the .NET stuff is deprecated. The new library (CEX++) is the one to follow.
It doesn't have standard NTRU, but instead NTRU prime, translated from the NIST PQ contest entry.
